[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "/"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERBOSE = "true"
  VITE_API_URL = "/api"
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  VITE_PUBLIC_URL = "/"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Required for SPA routing
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
