// This file will contain the service worker implementation for TypeScript

externalself; // Reference the external self object

export {}; // Export an empty module to avoid ESM issues

// Add placeholder for workbox manifest
self.__WB_MANIFEST = [];

// Import workbox modules
import { precacheAndRoute } from 'workbox-precaching';

// Precache assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);