name = "bra-elite"
main = "server/index.ts"
compatibility_date = "2024-01-01"

type = "javascript"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]

[site]
source = "client/dist"
entry-point = "server/index.ts"
bucket = "bra-elite-assets"

[build]
command = "npm run build"
watch_dir = "client/src"

[env.production]
vars = { ENVIRONMENT = "production" }

[[kv_namespaces]]
id = "bra-elite-kv"
preview_id = "bra-elite-kv-preview"
binding = "KV_STORE"

[[d1_databases]]
binding = "DB"
database_name = "bra-elite-db"
database_id = "bra-elite-db-id"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "bra-elite-assets"

[miniflare]
kv_persist = true
r2_persist = true
cache_persist = true

[triggers]
crons = ["0 0 * * *"] # Executa diariamente à meia-noite

[cache_settings]
cache_api = true
browser_ttl = 3600
cdn_ttl = 7200
custom_key = true